### ISSUE TITLE
Documentation for usage with Cloud platforms

### ISSUE THREAD

**Issue by behrica** [zero-one-group/geni#229]
I would like to use geni against a Spark cluster, running in Azure Kubernetes.
It seems to be an amazing tool.

Good new is, that it did work, but it was very tricky to get started on this.

I believe, it is mainly a question of missing documentation.

My main question, which I was struggling for a while, was to:

1) Understand firstly, if Geni should support it at all. I assumed it, but as the documentation only showcases local use, I was not sure about it.

2) When and where to call my own g/create-spark-session.  This was very tricky to discover, as

* its gets done "magically" somewhere lazily
* is  using clojure delay which is then somehow a global variable
* the session cannot be changed practically inside a running repl, ones it was set up
* The precise setup for this differs very likely between using the Geni CLI tool and working in a repl
* The documentation  mentions it somehow, but not very clear: https://github.com/zero-one-group/geni/blob/develop/docs/spark_session.md  . Specially it does not say, where and when this need to be  called and how it relates to the global https://github.com/zero-one-group/geni/blob/671510e1a42e5e5a9fc9c38392a029f569bdbecc/src/clojure/zero_one/geni/main.clj#L13
which is a "future" of a "delay" ....

I would propose to add one example documentation of using geny with a remote/ Cloud spark instance,
or maybe even show the full setup using a local minikube kubernetes cluster.
At least with minikube it is possible to create a "step-by-step" recipe, which can be copy-pasted into a shell.

(I know, Spark on kubernets is a very tricky issue by itself.)

**Comment by erp12** [comment]
I am also trying to answer these questions.  Currently I am working on getting Geni running on an AWS EC2 cluster that is managed with [flintrock](https://github.com/nchammas/flintrock). I think this will be a good first step, and a lot narrower than Kubernetes. Once I get it working, I plan on writing up a blog post.

I would be interested to hear more about your process to get a working Geni cluster on Azure Kubernetes.

**Comment by anthony-khong** [comment]
Hi @behrica, thanks for raising the issue! You're touching on a very important part of Geni's use case that, thus far, hasn't really been worked on. Contributions would be greatly appreciated 😁 

> I believe, it is mainly a question of missing documentation.

This is true, and, truth be told, not much work has been done on it. If you managed to get it working, please let us know how you did it! We should identify the pain points, address them (perhaps even making tradeoffs about how the local Geni works) and create a guide for others to use. 

I wrote a mini guide for GCP's Dataproc: https://github.com/zero-one-group/geni/blob/develop/docs/dataproc.md

> Understand firstly, if Geni should support it at all. I assumed it, but as the documentation only showcases local use, I was not sure about it.

Geni should absolutely support it. The idea is to fully leverage the Spark ecosystem, and computing on the cluster is what makes Spark awesome. The documentation only showcases local use, because that's the low hanging fruit, and we just haven't gotten around to clusters yet.

> When and where to call my own g/create-spark-session. This was very tricky to discover, as ...

Yep, totally understand. All of the docs and the CLI had `local[*]` in mind. We definitely need to work on it to make it usable on a cluster. Again, you pointed out valid points of confusion - for instance, the SparkSession is magically started as a `Future` to cut down seconds of start up time, which is useful in smaller datasets, but less so in a cluster setting. None of this is fixed, we can definitely change it!

> I would propose to add one example documentation of using geny with a remote/ Cloud spark instance,
or maybe even show the full setup using a local minikube kubernetes cluster. At least with minikube it is possible to create a "step-by-step" recipe, which can be copy-pasted into a shell.

That sounds awesome and super helpful! Would you be happy to contribute this? Otherwise, I'll put it on my backlog 😁

**Comment by behrica** [comment]
I could  eventually contribute a "example setup using minikube".

There are some key decisions regarding "which setup to showcase" to take, for which I  have found "one" answer, but I am not it is the  the best answer.

For example, in your dataproc exmaple you ssh into the cluster. This has for sure big advantages regarding security,
but It means I cannot use emacs... Unless I install it there as well (including my full emacs setup).

So I went a complete different route, namely running a clojure nrepl in the cluster, which is accessible remotely.
(better said: I proxied into by using kubectl)

An other big questions mark is the "lifespan" of the cluster nodes.
Most examples of Spark In Kubernetes are "job oriented". So the nodes are started and stopped  for each job.
This is a well possible with a repl, but maybe not the most usefull scenario.

Dependency management:  Eventually our analysis code needs extra jars. In kubernetes they need to become part of the "Docker images"

But I will try the simplest example using minikube + / Spark + geni.

**Comment by anthony-khong** [comment]
Hi @behrica, I believe there are potentially four interesting doc topics here, namely i) setting up geni on minikube, ii) connecting to the nrepl of a running server, iii) submitting geni jobs to a remote cluster and iv) adding jars to the minikube setup. Each one of this topic would be very useful in their own right!

**Comment by behrica** [comment]
Please find a short article of i) here. I can contribute it here.
https://github.com/behrica/geni/blob/develop/docs/kubernetes_basic.md

**Comment by behrica** [comment]
I would have one small follow up, 
which is on how to access data files living in Azure Blob Storage.

This requires:
1) adding jars to the Docker images
2) adding dependency to clojure command
3) configuring access to Azure blob storage
4) calling "read-csv!" in correct syntax for reading from Azure blob storage

Only now the data analysis can start .... :smile:

**Comment by anthony-khong** [comment]
Hi @behrica, this looks great! Thank you for taking the time to write it!

Would you like to make a PR to the main repo, and I can help to review it? You can then incrementally add the other parts 😄

Just from reading through it, here's a couple of typos and some minor style comments:

- https://github.com/behrica/geni/blob/develop/docs/kubernetes_basic.md#geni-on-kubernetes: computeter -> computer.
- https://github.com/behrica/geni/blob/develop/docs/kubernetes_basic.md#install-spark-distribution: spark -> Spark.
- https://github.com/behrica/geni/blob/develop/docs/kubernetes_basic.md#start-minikube: wrok -> work, teh -> the
- https://github.com/behrica/geni/blob/develop/docs/kubernetes_basic.md#create-docker-images: docker-imagetool.sh -> `docker-imagetool.sh`, "-m" -> `-m`.
- https://github.com/behrica/geni/blob/develop/docs/kubernetes_basic.md#setup-clojure-dependencies: org.apache.spark/spark_kubernetes_2.12 -> `org.apache.spark/spark_kubernetes_2.12`, and delete extra space on the code block.
- https://github.com/behrica/geni/blob/develop/docs/kubernetes_basic.md#create-spark-session: lower cases to start the bullet points, teh -> the, repl -> REPL

Also, should we also add the dependencies? Would one only need `minikube`? If so, should we add a link for its installation?

Thank you again, @behrica, this is awesome! I will try it myself soon!

**Comment by behrica** [comment]
I send a pull request with the basic kubernetes docu, and took your proposals into considerations.

**Comment by anthony-khong** [comment]
Hi @behrica, I believe you've solved this with your own PR, which has been merged. Would you be happy to close the issue? 😄
